[project]
name = "aws-operator-agent"
version = "0.2.0"
description = "AWS Operator Agent"
requires-python = ">=3.11"
dependencies = [
    "bedrock-agentcore",
    "boto3>=1.40.0",
    "botocore>=1.40.0",
]